import { ProductEntity } from "./interfaces.db";

export const products: ProductEntity[] = [
  {
    name: "Refrigerator",
    price: 223.36,
    type: "Home",
    brand: "LG",
    color: "Gray",
    size: "Medium",
  },
  {
    name: "T-shirt",
    price: 271.09,
    type: "Clothing",
    brand: "Nike",
    color: "Yellow",
    size: "Small",
  },
  {
    name: "Computer",
    price: 76.25,
    type: "Electronics",
    brand: "Sony",
    color: "Black",
    size: "Medium",
  },
  {
    name: "Phone",
    price: 215.11,
    type: "Electronics",
    brand: "Samsung",
    color: "Black",
    size: "Medium",
  },
  {
    name: "Pants",
    price: 154.16,
    type: "Clothing",
    brand: "Adidas",
    color: "Green",
    size: "Small",
  },
  {
    name: "Watch",
    price: 88.77,
    type: "Accessories",
    brand: "Nike",
    color: "Red",
    size: "Large",
  },
  {
    name: "Refrigerator",
    price: 349.22,
    type: "Home",
    brand: "LG",
    color: "White",
    size: "Small",
  },
  {
    name: "Bag",
    price: 195.71,
    type: "Accessories",
    brand: "Zara",
    color: "Yellow",
    size: "Large",
  },
  {
    name: "Pants",
    price: 482.96,
    type: "Clothing",
    brand: "Zara",
    color: "Red",
    size: "Small",
  },
  {
    name: "Table",
    price: 215.81,
    type: "Home",
    brand: "Zara",
    color: "Black",
    size: "Large",
  },
  {
    name: "Chair",
    price: 63.56,
    type: "Home",
    brand: "Xiaomi",
    color: "White",
    size: "Large",
  },
  {
    name: "Shoes",
    price: 346.81,
    type: "Clothing",
    brand: "Adidas",
    color: "Yellow",
    size: "Medium",
  },
  {
    name: "Pants",
    price: 192.43,
    type: "Clothing",
    brand: "H&M",
    color: "Black",
    size: "Small",
  },
  {
    name: "Chair",
    price: 293.06,
    type: "Home",
    brand: "H&M",
    color: "White",
    size: "Small",
  },
  {
    name: "Computer",
    price: 415.91,
    type: "Electronics",
    brand: "HP",
    color: "Blue",
    size: "Large",
  },
  {
    name: "Refrigerator",
    price: 152.32,
    type: "Home",
    brand: "Sony",
    color: "White",
    size: "Small",
  },
  {
    name: "Shoes",
    price: 404.57,
    type: "Clothing",
    brand: "Nike",
    color: "Purple",
    size: "Large",
  },
  {
    name: "Phone",
    price: 237.54,
    type: "Electronics",
    brand: "Xiaomi",
    color: "Blue",
    size: "Medium",
  },
  {
    name: "Refrigerator",
    price: 163.73,
    type: "Home",
    brand: "LG",
    color: "Gray",
    size: "Medium",
  },
  {
    name: "Phone",
    price: 70.82,
    type: "Electronics",
    brand: "Sony",
    color: "Green",
    size: "Large",
  },
  {
    name: "Refrigerator",
    price: 224.09,
    type: "Home",
    brand: "LG",
    color: "Yellow",
    size: "Large",
  },
  {
    name: "Watch",
    price: 121.46,
    type: "Accessories",
    brand: "Adidas",
    color: "Blue",
    size: "Medium",
  },
  {
    name: "Bag",
    price: 31.36,
    type: "Accessories",
    brand: "Zara",
    color: "Black",
    size: "Small",
  },
  {
    name: "Phone",
    price: 294.27,
    type: "Electronics",
    brand: "Samsung",
    color: "Purple",
    size: "Medium",
  },
  {
    name: "T-shirt",
    price: 99.55,
    type: "Clothing",
    brand: "Zara",
    color: "White",
    size: "Medium",
  },
];
