import { IProductEntity } from "./interfaces.db";
import { productTypes } from "./productTypes.db";
import { brands } from "./brands.db";

export const products: IProductEntity[] = [
  {
    id: undefined,
    name: "Refrigerator",
    price: 223.36,
    productType: productTypes.find(pt => pt.name ===  "Home"),
    brand: brands.find(br => br.name ===  "LG"),
    color: "Gray",
    size: "Medium",
  },
  {
    id: undefined,
    name: "T-shirt",
    price: 271.09,
    productType: productTypes.find(pt => pt.name ===  "Clothing"),
    brand: brands.find(br => br.name ===  "Nike"),
    color: "Yellow",
    size: "Small",
  },
  {
    id: undefined,
    name: "Computer",
    price: 76.25,
    productType: productTypes.find(pt => pt.name ===  "Electronics"),
    brand: brands.find(br => br.name ===  "Sony"),
    color: "Black",
    size: "Medium",
  },
  {
    id: undefined,
    name: "Phone",
    price: 215.11,
    productType: productTypes.find(pt => pt.name ===  "Electronics"),
    brand: brands.find(br => br.name ===  "Samsung"),
    color: "Black",
    size: "Medium",
  },
  {
    id: undefined,
    name: "Pants",
    price: 154.16,
    productType: productTypes.find(pt => pt.name ===  "Clothing"),
    brand: brands.find(br => br.name ===  "Adidas"),
    color: "Green",
    size: "Small",
  },
  {
    id: undefined,
    name: "Watch",
    price: 88.77,
    productType: productTypes.find(pt => pt.name ===  "Accessories"),
    brand: brands.find(br => br.name ===  "Nike"),
    color: "Red",
    size: "Large",
  },
  {
    id: undefined,
    name: "Refrigerator",
    price: 349.22,
    productType: productTypes.find(pt => pt.name ===  "Home"),
    brand: brands.find(br => br.name ===  "LG"),
    color: "White",
    size: "Small",
  },
  {
    id: undefined,
    name: "Bag",
    price: 195.71,
    productType: productTypes.find(pt => pt.name ===  "Accessories"),
    brand: brands.find(br => br.name ===  "Zara"),
    color: "Yellow",
    size: "Large",
  },
  {
    id: undefined,
    name: "Pants",
    price: 482.96,
    productType: productTypes.find(pt => pt.name ===  "Clothing"),
    brand: brands.find(br => br.name ===  "Zara"),
    color: "Red",
    size: "Small",
  },
  {
    id: undefined,
    name: "Table",
    price: 215.81,
    productType: productTypes.find(pt => pt.name ===  "Home"),
    brand: brands.find(br => br.name ===  "Zara"),
    color: "Black",
    size: "Large",
  },
  {
    id: undefined,
    name: "Chair",
    price: 63.56,
    productType: productTypes.find(pt => pt.name ===  "Home"),
    brand: brands.find(br => br.name ===  "Xiaomi"),
    color: "White",
    size: "Large",
  },
  {
    id: undefined,
    name: "Shoes",
    price: 346.81,
    productType: productTypes.find(pt => pt.name ===  "Clothing"),
    brand: brands.find(br => br.name ===  "Adidas"),
    color: "Yellow",
    size: "Medium",
  },
  {
    id: undefined,
    name: "Pants",
    price: 192.43,
    productType: productTypes.find(pt => pt.name ===  "Clothing"),
    brand: brands.find(br => br.name ===  "H&M"),
    color: "Black",
    size: "Small",
  },
  {
    id: undefined,
    name: "Chair",
    price: 293.06,
    productType: productTypes.find(pt => pt.name ===  "Home"),
    brand: brands.find(br => br.name ===  "H&M"),
    color: "White",
    size: "Small",
  },
  {
    id: undefined,
    name: "Computer",
    price: 415.91,
    productType: productTypes.find(pt => pt.name ===  "Electronics"),
    brand: brands.find(br => br.name ===  "HP"),
    color: "Blue",
    size: "Large",
  },
  {
    id: undefined,
    name: "Refrigerator",
    price: 152.32,
    productType: productTypes.find(pt => pt.name ===  "Home"),
    brand: brands.find(br => br.name ===  "Sony"),
    color: "White",
    size: "Small",
  },
  {
    id: undefined,
    name: "Shoes",
    price: 404.57,
    productType: productTypes.find(pt => pt.name ===  "Clothing"),
    brand: brands.find(br => br.name ===  "Nike"),
    color: "Purple",
    size: "Large",
  },
  {
    id: undefined,
    name: "Phone",
    price: 237.54,
    productType: productTypes.find(pt => pt.name ===  "Electronics"),
    brand: brands.find(br => br.name ===  "Xiaomi"),
    color: "Blue",
    size: "Medium",
  },
  {
    id: undefined,
    name: "Refrigerator",
    price: 163.73,
    productType: productTypes.find(pt => pt.name ===  "Home"),
    brand: brands.find(br => br.name ===  "LG"),
    color: "Gray",
    size: "Medium",
  },
  {
    id: undefined,
    name: "Phone",
    price: 70.82,
    productType: productTypes.find(pt => pt.name ===  "Electronics"),
    brand: brands.find(br => br.name ===  "Sony"),
    color: "Green",
    size: "Large",
  },
  {
    id: undefined,
    name: "Refrigerator",
    price: 224.09,
    productType: productTypes.find(pt => pt.name ===  "Home"),
    brand: brands.find(br => br.name ===  "LG"),
    color: "Yellow",
    size: "Large",
  },
  {
    id: undefined,
    name: "Watch",
    price: 121.46,
    productType: productTypes.find(pt => pt.name ===  "Accessories"),
    brand: brands.find(br => br.name ===  "Adidas"),
    color: "Blue",
    size: "Medium",
  },
  {
    id: undefined,
    name: "Bag",
    price: 31.36,
    productType: productTypes.find(pt => pt.name ===  "Accessories"),
    brand: brands.find(br => br.name ===  "Zara"),
    color: "Black",
    size: "Small",
  },
  {
    id: undefined,
    name: "Phone",
    price: 294.27,
    productType: productTypes.find(pt => pt.name ===  "Electronics"),
    brand: brands.find(br => br.name ===  "Samsung"),
    color: "Purple",
    size: "Medium",
  },
  {
    id: undefined,
    name: "T-shirt",
    price: 99.55,
    productType: productTypes.find(pt => pt.name ===  "Clothing"),
    brand: brands.find(br => br.name ===  "Zara"),
    color: "White",
    size: "Medium",
  },
];
